In [1]:
g =lambda x:x+1

In [2]:
g(1)

2

In [3]:
g(2)

3

In [7]:
def gg(x):
    return x+1

In [8]:
gg(1)

2

In [2]:
import numpy as np
x=np.array([1,2])
len(x.shape)

1

In [3]:
def my_func(a):
    return (a[0]+a[-1])*0.5

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.apply_along_axis(my_func,0,b)   #0按行走

array([ 4.,  5.,  6.])

In [6]:
np.apply_along_axis(my_func,1,b)   # 1按列走

array([ 2.,  5.,  8.])

In [7]:
b=np.array([[8,1,7],[4,3,9],[5,2,9]])
np.apply_along_axis(sorted,1,b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 9]])

In [8]:
np.apply_along_axis(sorted,0,b)

array([[4, 1, 7],
       [5, 2, 9],
       [8, 3, 9]])

In [16]:
b=np.array([1,2,3])
print(b.shape)
np.apply_along_axis(np.diag,-1,b)

(3,)


ValueError: could not broadcast input array from shape (3,3) into shape (3)